
server:
  port: 9091
spring:
  application:
    name: Client1
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true   
    service-url:
      defaultZone: http://localhost:8761/eureka   
  
     
  
